server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/board.access.log;
    error_log /var/log/nginx/board.error.log;

    include /etc/nginx/app-locations/*.conf;

    location / {
        return 404;
    }
}
